import { DashboardData, PushedRepository, AttentionItem, ActivityTimelineItem } from '../types/app';
import { GitHubPullRequest, GitHubUser, GitHubOrganization, GitHubRepository } from '../types/github';

const now = Date.now();
const minutesAgo = (mins: number) => new Date(now - mins * 60 * 1000).toISOString();
const hoursAgo = (hours: number) => new Date(now - hours * 60 * 60 * 1000).toISOString();
const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_USER: GitHubUser = {
  login: 'samirpatil2000',
  id: 4829103,
  node_id: 'MDQ6VXNlcjQ4MjkxMDM=',
  avatar_url: 'https://avatars.githubusercontent.com/u/4829103?v=4',
  html_url: 'https://github.com/samirpatil2000',
  name: 'Samir Patil',
  company: 'Narkane / Independent',
  blog: 'https://samirpatil.dev',
  location: 'San Francisco, CA',
  email: 'samir@example.com',
  bio: 'Building AI tools, developer cockpits & 3D procedural systems.',
  public_repos: 28,
  total_private_repos: 14,
  owned_private_repos: 8,
};

export const MOCK_ORGANIZATIONS: GitHubOrganization[] = [
  {
    login: 'Narkane',
    id: 9102834,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjkxMDI4MzQ=',
    url: 'https://api.github.com/orgs/Narkane',
    avatar_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    description: 'Generative AI & creative media tools',
  },
  {
    login: 'Acme',
    id: 5729104,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbTU3MjkxMDQ=',
    url: 'https://api.github.com/orgs/Acme',
    avatar_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=100&auto=format&fit=crop&q=80',
    description: 'Enterprise workflow systems',
  },
];

export const MOCK_LATEST_PUSHES: PushedRepository[] = [
  {
    id: 101,
    name: 'environment-sculptor',
    fullName: 'Narkane/environment-sculptor',
    owner: 'Narkane',
    ownerAvatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    isOrg: true,
    visibility: 'private',
    branch: 'main',
    latestCommitMessage: 'Add procedural camera track interpolation',
    latestCommitSha: '8a3f12d89b12480a8274092b7c4a12390f7a6b32',
    shortSha: '8a3f12d',
    pushedAt: minutesAgo(12),
    commitCount: 3,
    language: 'TypeScript',
    repoUrl: 'https://github.com/Narkane/environment-sculptor',
    commitUrl: 'https://github.com/Narkane/environment-sculptor/commit/8a3f12d',
    branchUrl: 'https://github.com/Narkane/environment-sculptor/tree/main',
    defaultBranch: 'main',
    openIssuesCount: 4,
    openPrCount: 2,
  },
  {
    id: 102,
    name: 'camera-path-fix',
    fullName: 'Narkane/camera-path-fix',
    owner: 'Narkane',
    ownerAvatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    isOrg: true,
    visibility: 'private',
    branch: 'feature/camera-recording',
    latestCommitMessage: 'Fix WebM frame timing synchronization in offline recording',
    latestCommitSha: 'c4b9e81aa098bc541123490987af54231b12480a',
    shortSha: 'c4b9e81',
    pushedAt: minutesAgo(34),
    commitCount: 1,
    language: 'TypeScript',
    repoUrl: 'https://github.com/Narkane/camera-path-fix',
    commitUrl: 'https://github.com/Narkane/camera-path-fix/commit/c4b9e81',
    branchUrl: 'https://github.com/Narkane/camera-path-fix/tree/feature/camera-recording',
    defaultBranch: 'main',
    openIssuesCount: 1,
    openPrCount: 1,
  },
  {
    id: 103,
    name: 'website',
    fullName: 'samirpatil2000/website',
    owner: 'samirpatil2000',
    ownerAvatarUrl: 'https://avatars.githubusercontent.com/u/4829103?v=4',
    isOrg: false,
    visibility: 'public',
    branch: 'main',
    latestCommitMessage: 'Update portfolio layout and dark mode contrast tokens',
    latestCommitSha: '19df3e4817a80b8274092b7c4a12390f7a6b328a',
    shortSha: '19df3e4',
    pushedAt: hoursAgo(1),
    commitCount: 2,
    language: 'TypeScript',
    repoUrl: 'https://github.com/samirpatil2000/website',
    commitUrl: 'https://github.com/samirpatil2000/website/commit/19df3e4',
    branchUrl: 'https://github.com/samirpatil2000/website/tree/main',
    defaultBranch: 'main',
    openIssuesCount: 0,
    openPrCount: 1,
  },
  {
    id: 104,
    name: 'backend-api',
    fullName: 'Acme/backend-api',
    owner: 'Acme',
    ownerAvatarUrl: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=100&auto=format&fit=crop&q=80',
    isOrg: true,
    visibility: 'private',
    branch: 'develop',
    latestCommitMessage: 'Implement token validation and rate limit response headers',
    latestCommitSha: '7fe2a099bc541123490987af54231b12480ac4b9',
    shortSha: '7fe2a09',
    pushedAt: hoursAgo(3),
    commitCount: 5,
    language: 'Go',
    repoUrl: 'https://github.com/Acme/backend-api',
    commitUrl: 'https://github.com/Acme/backend-api/commit/7fe2a09',
    branchUrl: 'https://github.com/Acme/backend-api/tree/develop',
    defaultBranch: 'develop',
    openIssuesCount: 8,
    openPrCount: 3,
  },
  {
    id: 105,
    name: 'viewer-template',
    fullName: 'Narkane/viewer-template',
    owner: 'Narkane',
    ownerAvatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    isOrg: true,
    visibility: 'public',
    branch: 'feat/catmull-rom',
    latestCommitMessage: 'Support dual-track timeline dock and frame-accurate scrubber',
    latestCommitSha: '4d2c88b8a3f12d89b12480a8274092b7c4a12390',
    shortSha: '4d2c88b',
    pushedAt: hoursAgo(5),
    commitCount: 2,
    language: 'JavaScript',
    repoUrl: 'https://github.com/Narkane/viewer-template',
    commitUrl: 'https://github.com/Narkane/viewer-template/commit/4d2c88b',
    branchUrl: 'https://github.com/Narkane/viewer-template/tree/feat/catmull-rom',
    defaultBranch: 'main',
    openIssuesCount: 2,
    openPrCount: 1,
  },
];

export const MOCK_ATTENTION_ITEMS: AttentionItem[] = [
  {
    id: 'att-1',
    reason: 'changes_requested',
    reasonLabel: 'Changes requested',
    prNumber: 184,
    prTitle: 'feat: Dual track timeline dock and camera flight controls',
    repoName: 'viewer-template',
    repoFullName: 'Narkane/viewer-template',
    owner: 'Narkane',
    author: 'samirpatil2000',
    authorAvatarUrl: 'https://avatars.githubusercontent.com/u/4829103?v=4',
    url: 'https://github.com/Narkane/viewer-template/pull/184',
    updatedAt: minutesAgo(25),
    details: 'Requested by @alex-dev',
    badgeType: 'danger',
  },
  {
    id: 'att-2',
    reason: 'review_requested',
    reasonLabel: 'Review requested',
    prNumber: 91,
    prTitle: 'refactor: Procedural mesh instancing pipeline',
    repoName: 'environment-sculptor',
    repoFullName: 'Narkane/environment-sculptor',
    owner: 'Narkane',
    author: 'sarah-lead',
    authorAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    url: 'https://github.com/Narkane/environment-sculptor/pull/91',
    updatedAt: hoursAgo(1),
    details: 'Requested by @sarah-lead',
    badgeType: 'warning',
  },
  {
    id: 'att-3',
    reason: 'checks_failing',
    reasonLabel: 'Checks failing',
    prNumber: 42,
    prTitle: 'refactor: Dark mode contrast tokens and system theme sync',
    repoName: 'website',
    repoFullName: 'samirpatil2000/website',
    owner: 'samirpatil2000',
    author: 'samirpatil2000',
    authorAvatarUrl: 'https://avatars.githubusercontent.com/u/4829103?v=4',
    url: 'https://github.com/samirpatil2000/website/pull/42',
    updatedAt: hoursAgo(2),
    details: 'Failed: build-and-test / typecheck',
    badgeType: 'danger',
  },
];

export const MOCK_OPEN_PRS: GitHubPullRequest[] = [
  {
    id: 901,
    node_id: 'PR_kwDO1234',
    html_url: 'https://github.com/Narkane/viewer-template/pull/184',
    number: 184,
    state: 'open',
    locked: false,
    title: 'feat: Dual track timeline dock and camera flight controls',
    user: MOCK_USER,
    body: 'Implements dual track timeline dock with frame accurate WebM scrubber.',
    created_at: daysAgo(2),
    updated_at: minutesAgo(25),
    closed_at: null,
    merged_at: null,
    merge_commit_sha: null,
    draft: false,
    head: {
      label: 'feat/catmull-rom',
      ref: 'feat/catmull-rom',
      sha: '4d2c88b',
      user: MOCK_USER,
      repo: null,
    },
    base: {
      label: 'main',
      ref: 'main',
      sha: '99a0b1c',
      user: MOCK_USER,
      repo: {
        id: 105,
        node_id: 'R_105',
        name: 'viewer-template',
        full_name: 'Narkane/viewer-template',
        private: false,
        owner: {
          login: 'Narkane',
          id: 9102834,
          avatar_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
          type: 'Organization',
        },
        html_url: 'https://github.com/Narkane/viewer-template',
        description: 'Interactive 3D WebGL viewer',
        fork: false,
        url: '',
        created_at: '',
        updated_at: '',
        pushed_at: '',
        homepage: null,
        size: 100,
        stargazers_count: 34,
        watchers_count: 34,
        language: 'JavaScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 2,
        archived: false,
        disabled: false,
        open_issues_count: 2,
        default_branch: 'main',
      },
    },
    labels: [
      { id: 1, name: 'enhancement', color: 'a2eeef', description: 'New feature' },
      { id: 2, name: '3d-viewer', color: '1d76db', description: 'Viewer module' },
    ],
    comments: 4,
    review_comments: 2,
    commits: 3,
    additions: 420,
    deletions: 85,
    changed_files: 8,
    mergeable: true,
  },
  {
    id: 902,
    node_id: 'PR_kwDO1235',
    html_url: 'https://github.com/samirpatil2000/website/pull/42',
    number: 42,
    state: 'open',
    locked: false,
    title: 'refactor: Dark mode contrast tokens and system theme sync',
    user: MOCK_USER,
    body: 'Refines typography scale, high contrast tokens, and automatic dark mode synchronization.',
    created_at: daysAgo(1),
    updated_at: hoursAgo(2),
    closed_at: null,
    merged_at: null,
    merge_commit_sha: null,
    draft: false,
    head: {
      label: 'fix/dark-mode',
      ref: 'fix/dark-mode',
      sha: '19df3e4',
      user: MOCK_USER,
      repo: null,
    },
    base: {
      label: 'main',
      ref: 'main',
      sha: '88a1b2c',
      user: MOCK_USER,
      repo: {
        id: 103,
        node_id: 'R_103',
        name: 'website',
        full_name: 'samirpatil2000/website',
        private: false,
        owner: {
          login: 'samirpatil2000',
          id: 4829103,
          avatar_url: 'https://avatars.githubusercontent.com/u/4829103?v=4',
          type: 'User',
        },
        html_url: 'https://github.com/samirpatil2000/website',
        description: 'Personal developer website & portfolio',
        fork: false,
        url: '',
        created_at: '',
        updated_at: '',
        pushed_at: '',
        homepage: null,
        size: 50,
        stargazers_count: 12,
        watchers_count: 12,
        language: 'TypeScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: true,
        forks_count: 0,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        default_branch: 'main',
      },
    },
    labels: [
      { id: 3, name: 'ui/ux', color: 'c5def5', description: 'Design updates' },
    ],
    comments: 2,
    review_comments: 0,
    commits: 2,
    additions: 110,
    deletions: 40,
    changed_files: 4,
    mergeable: true,
  },
  {
    id: 903,
    node_id: 'PR_kwDO1236',
    html_url: 'https://github.com/Acme/backend-api/pull/91',
    number: 91,
    state: 'open',
    locked: false,
    title: 'feat: Add GraphQL schema for timeline queries and batch events',
    user: MOCK_USER,
    body: 'Adds GraphQL schema resolvers for client dashboard event aggregation.',
    created_at: hoursAgo(6),
    updated_at: hoursAgo(3),
    closed_at: null,
    merged_at: null,
    merge_commit_sha: null,
    draft: true,
    head: {
      label: 'feat/timeline-graphql',
      ref: 'feat/timeline-graphql',
      sha: '7fe2a09',
      user: MOCK_USER,
      repo: null,
    },
    base: {
      label: 'develop',
      ref: 'develop',
      sha: '33b4c5d',
      user: MOCK_USER,
      repo: {
        id: 104,
        node_id: 'R_104',
        name: 'backend-api',
        full_name: 'Acme/backend-api',
        private: true,
        owner: {
          login: 'Acme',
          id: 5729104,
          avatar_url: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?w=100&auto=format&fit=crop&q=80',
          type: 'Organization',
        },
        html_url: 'https://github.com/Acme/backend-api',
        description: 'Backend services & API gateway',
        fork: false,
        url: '',
        created_at: '',
        updated_at: '',
        pushed_at: '',
        homepage: null,
        size: 500,
        stargazers_count: 5,
        watchers_count: 5,
        language: 'Go',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 1,
        archived: false,
        disabled: false,
        open_issues_count: 8,
        default_branch: 'develop',
      },
    },
    labels: [
      { id: 4, name: 'backend', color: 'fbca04', description: 'Backend service' },
      { id: 5, name: 'wip', color: 'ededed', description: 'Work in progress' },
    ],
    comments: 0,
    review_comments: 0,
    commits: 5,
    additions: 680,
    deletions: 120,
    changed_files: 12,
    mergeable: true,
  },
];

export const MOCK_RECENT_ACTIVITY: ActivityTimelineItem[] = [
  {
    id: 'act-1',
    type: 'push',
    typeLabel: 'Pushed 3 commits',
    title: 'environment-sculptor',
    repoName: 'environment-sculptor',
    repoFullName: 'Narkane/environment-sculptor',
    ref: 'main',
    timestamp: minutesAgo(12),
    url: 'https://github.com/Narkane/environment-sculptor/tree/main',
    details: 'Add procedural camera track interpolation',
    badgeType: 'push',
  },
  {
    id: 'act-2',
    type: 'review_requested',
    typeLabel: 'Requested review',
    title: 'viewer-template #184',
    repoName: 'viewer-template',
    repoFullName: 'Narkane/viewer-template',
    ref: '#184',
    timestamp: hoursAgo(1),
    url: 'https://github.com/Narkane/viewer-template/pull/184',
    details: 'feat: Dual track timeline dock',
    badgeType: 'review',
  },
  {
    id: 'act-3',
    type: 'review_submitted',
    typeLabel: 'Approved',
    title: 'website #42',
    repoName: 'website',
    repoFullName: 'samirpatil2000/website',
    ref: '#42',
    timestamp: hoursAgo(2),
    url: 'https://github.com/samirpatil2000/website/pull/42',
    details: 'Dark mode tokens look clean and crisp',
    badgeType: 'review',
  },
  {
    id: 'act-4',
    type: 'pr_opened',
    typeLabel: 'Opened',
    title: 'backend-api #91',
    repoName: 'backend-api',
    repoFullName: 'Acme/backend-api',
    ref: '#91',
    timestamp: hoursAgo(3),
    url: 'https://github.com/Acme/backend-api/pull/91',
    details: 'feat: Add GraphQL schema for timeline queries',
    badgeType: 'pr',
  },
  {
    id: 'act-5',
    type: 'push',
    typeLabel: 'Pushed 1 commit',
    title: 'camera-path-fix',
    repoName: 'camera-path-fix',
    repoFullName: 'Narkane/camera-path-fix',
    ref: 'feature/camera-recording',
    timestamp: hoursAgo(4),
    url: 'https://github.com/Narkane/camera-path-fix/tree/feature/camera-recording',
    details: 'Fix WebM frame timing synchronization',
    badgeType: 'push',
  },
];

export const MOCK_REPOSITORIES: GitHubRepository[] = [
  ...MOCK_LATEST_PUSHES.map((p) => ({
    id: p.id,
    node_id: `R_${p.id}`,
    name: p.name,
    full_name: p.fullName,
    private: p.visibility === 'private',
    owner: {
      login: p.owner,
      id: p.isOrg ? 9102834 : 4829103,
      avatar_url: p.ownerAvatarUrl || '',
      type: (p.isOrg ? 'Organization' : 'User') as 'User' | 'Organization',
    },
    html_url: p.repoUrl,
    description: p.latestCommitMessage,
    fork: false,
    url: p.repoUrl,
    created_at: daysAgo(30),
    updated_at: p.pushedAt,
    pushed_at: p.pushedAt,
    homepage: null,
    size: 240,
    stargazers_count: 18,
    watchers_count: 18,
    language: p.language,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 3,
    archived: false,
    disabled: false,
    open_issues_count: p.openIssuesCount || 0,
    default_branch: p.defaultBranch || 'main',
    visibility: p.visibility,
  })),
];

export const MOCK_DASHBOARD_DATA: DashboardData = {
  user: MOCK_USER,
  organizations: MOCK_ORGANIZATIONS,
  latestPushes: MOCK_LATEST_PUSHES,
  attentionItems: MOCK_ATTENTION_ITEMS,
  myOpenPrs: MOCK_OPEN_PRS,
  recentActivity: MOCK_RECENT_ACTIVITY,
  repositories: MOCK_REPOSITORIES,
  lastSyncedAt: minutesAgo(2),
  rateLimit: {
    limit: 5000,
    remaining: 4892,
    resetTime: new Date(now + 45 * 60 * 1000).toISOString(),
    resetInMinutes: 45,
    isLimited: false,
  },
  isLoading: false,
  isRefreshing: false,
  error: null,
  isMockData: true,
};
